# Generated by Django 5.0.2 on 2024-04-08 20:24

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo_app', '0004_alter_counties_geom'),
    ]

    operations = [
        migrations.CreateModel(
            name='Raster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raster_name', models.CharField(max_length=50, null=True)),
                ('resolution', models.FloatField(null=True)),
                ('year', models.IntegerField(null=True)),
                ('file', models.FileField(null=True, upload_to='Rasters/', verbose_name='Tiff')),
                ('sld_file', models.FileField(blank=True, null=True, upload_to='Rasters/Style', verbose_name='sld')),
                ('uploaded_date', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Rasters',
            },
        ),
        migrations.AlterField(
            model_name='counties',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=-1),
        ),
    ]
